In [9]:
import numpy as np
from numpy.linalg import matrix_power

In [10]:
fl = np.array([
    [.1,.8,.6],
    [.5,.7,.5],
    [.2,.2,.8]
])
layer = np.random.rand(6,6)
layer = layer.round(1)

def manual_conv2D(layer, stride, fl, padding):
    f_size = len(fl)
    rows, cols = np.shape(layer) #layerin olculerini aliriq
    
    #padding tetbiq edirik

    padded_layer = np.zeros((rows + (padding*2), cols + (padding*2)))
    padded_layer[padding: rows+padding, padding: cols+padding] = layer

    # print(layer)
    # print(padded_array)

    #padding tetbiq olunmush layerin yeni olchulerini aliriq
    rows, cols = np.shape(padded_layer)

    #conv
    r = int((rows - f_size)/stride + 1) # yeni layerin row sayisi
    cl = int((cols - f_size)/stride + 1) # yeni layerin column sayisi

    conv2d_layer = np.zeros((r, cl))
    
    for i in range(0, r, stride):
        for j in range(0, cl, stride):
            res = round(np.sum(np.multiply(padded_layer[i: i+f_size, j: j+f_size], fl)), 2)
            conv2d_layer[i][j] = res
    
    return conv2d_layer


result = manual_conv2D(layer, 1, fl, 1)
# print(np.shape(result))
# print(result)

In [11]:
# Pooling method
def manual_pooling(layer, stride, kernel):
    rows, cols = np.shape(layer) #layerin olculeri

    r = int((rows - kernel)/stride + 1) 
    cl = int((cols - kernel)/stride + 1) 
    
    pooled_layer = np.zeros((r, cl))
    
    for i in range(r):
        for j in range(cl):
            res = np.amax(layer[i:i+kernel, j:j+kernel]) #max pooling
            # res = np.amin(layer[i:i+kernel, j:j+kernel]) #min pooling
            # res = round(np.average(layer[i:i+kernel, j:j+kernel]), 2) #average pooling
            pooled_layer[i][j] = res

    return pooled_layer

# print(layer)
# print(manual_pooling(layer, 1, 3)) 


# Flatten method

# layer = np.random.rand(10, 10)
# layer = layer.round(1)


def manual_flatten(matrix):
    res = np.array([])
    for i in range(len(matrix)):
        res = np.insert(res, len(res), matrix[i])
    return res

# print(manual_flatten(layer))

In [12]:
#Question 9
I = np.array([
    [
        [2, 1, 2, 0, 0, 1],
        [-1, 0, 1, -2, 0, 4],
        [0, 0, 0, 3, 0, 0],
        [0, 0, -1, 1, 1, 2],
        [2, 0, 0, 6, 0, 0],
        [1, 0, 0, 0, -1, 1]
    ], 
    [
        [0, 1, 2, 1, 0, 1],
        [-3, 2, 0, 1, 2, 1],
        [0, 3, 1, -3, 0, 1],
        [1, 0, -2, 0, 0, 0],
        [0, 1, -1, 1, 0, 1],
        [0, 0, 4, 1, 2, 1]
    ]
])

K = np.array([
    [
        [1,1], 
        [1,0]
    ],
    [
        [3,0], 
        [0,1]
    ]
])

I_0_conv = manual_conv2D(I[0], 1, K[0], 1)
# print(I_0_conv)
I_1_conv = manual_conv2D(I[1], 1, K[1], 1)
#print(I_1_conv)

last_I = I_0_conv + I_1_conv
# print(last_I)

pooled_I = manual_pooling(last_I,1,2)
# print(pooled_I)

flattened_I = manual_flatten(pooled_I)
print(flattened_I)

[ 4.  6. 10. 10.  3.  8.  4.  8. 10. 10. 11. 11.  1.  8.  8.  5. 11. 11.
  6.  7.  7.  8.  8.  5.  6.  7.  7. 11. 11.  4.  3.  7. 12. 12. 11.  6.]


In [13]:
#padding
# an_array = np.array([[2, 0, -1, 5, 1], 
#     [0, 0, 0, -1, 1], 
#     [4, 1, 1, -1, 0], 
#     [3, 0, 1, 0, 1], 
#     [1, 2, 1, 1, 0]])
# en, uzun = np.shape(an_array)
# pad = 2
# print(en, uzun)
# padded_array = np.zeros((en+(pad*2),uzun+(pad*2)))
# padded_array[pad:en+pad,pad:uzun+pad] = an_array
# print(padded_array)

In [14]:
#Question 8

input_layer = np.array([
    [2, 0, -1, 5, 1], 
    [0, 0, 0, -1, 1], 
    [4, 1, 1, -1, 0], 
    [3, 0, 1, 0, 1], 
    [1, 2, 1, 1, 0]
])

fltr = np.array([
    [-1, 0, 1],
    [1, 3, 0],
    [1, 2, 0]
])

print(np.shape(input_layer))

output_layer = manual_conv2D(input_layer, 1, fltr, 1)


print( 'X is: ', output_layer[2,0])
print('Y is: ', output_layer[1,1])
print(output_layer)

(5, 5)
X is:  18.0
Y is:  3.0
[[ 6.  2. -3. 12.  9.]
 [ 8.  3.  8. -2. -4.]
 [18. 10.  5.  0.  2.]
 [12.  5.  5.  3.  5.]
 [ 3.  5.  5.  4.  1.]]


In [15]:
#question 10
#Question 10
from numpy.linalg import matrix_power

T = np.array([
    [.25, .15, .2, .1, .17, .23],
    [.13, .1, .15, .05, .17, .4],
    [.2, .25, .15, .15, .2, .05], 
    [.3, .15, .17, .25, .1, .2], 
    [.23, .05, .17, .25, .1, .2], 
    [.2, .15, .15, .1, .15, .25]

])

n1, n2 = 2, 5 #number of steps

print(T[0:6, 1])


T = matrix_power(T, n1)
T = T.round(2)
# print(T)
print('after', n1, 'steps' )
# print(T)
print('P3: ', T[0:6, 1])
print('P6: ', T[0:6, 4])

T = matrix_power(T, n2)
T = T.round(2)
# print(T)
print('after', n2, 'steps' )
print('P3: ', T[0:6, 1])
print('P6: ', T[0:6, 4])

[0.15 0.1  0.25 0.15 0.05 0.15]
after 2 steps
P3:  [0.16 0.14 0.13 0.18 0.15 0.14]
P6:  [0.17 0.15 0.15 0.18 0.15 0.15]
after 5 steps
P3:  [0.22 0.2  0.2  0.25 0.21 0.2 ]
P6:  [0.24 0.21 0.22 0.26 0.22 0.21]


In [16]:
# Question 10 - Part 2


tr = np.array([
    [.25, .15, .2, .1, .17, .23],
    [.13, .1, .15, .05, .17, .4],
    [.2, .25, .15, .15, .2, .05], 
    [.3, .15, .17, .25, .1, .2], 
    [.23, .05, .17, .25, .1, .2], 
    [.2, .15, .15, .1, .15, .25]

])

Previous = np.zeros((len(tr), len(tr))) 
copy = tr
c = 1

while((Previous != tr).all()):
    Previous = tr
    tr = np.dot(tr, copy)
    c+=1

tr = tr.round(2)
print(c)

16416


<ipython-input-16-a77466dfc7bf>:23: RuntimeWarning: overflow encountered in multiply
  tr = tr.round(2)
